// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzumiaemlebjkgdtymqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dW1pYWVtbGViamtnZHR5bXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjQzNjUsImV4cCI6MjA3NDAwMDM2NX0.WbVs3su2QFaSSjpK4tzTtkZ3jFHUV5phaqelecl_63U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});